name: notification
description: >
  Implement the Notification element using JS interop
version: 0.0.1
homepage: https://github.com/google/notification.dart
environment:
  sdk: '>=1.0.0 <2.0.0'
author: Dart Team <misc@dartlang.org>
dependencies:
  browser: '>=0.10.0 <0.11.0'
dev_dependencies:
  unittest: '>=0.10.0 <0.12.0'