name: web_notifications
description: >
  Implement the Web Notifications spec using JS interop
version: 0.0.3
homepage: https://github.com/google/web_notifications.dart
environment:
  sdk: '>=1.0.0 <2.0.0'
author: Dart Team <misc@dartlang.org>
dependencies:
  browser: '>=0.10.0 <0.11.0'
dev_dependencies:
  unittest: '>=0.10.0 <0.12.0'
